version: '3.9'

services:
  ch:
    image: yandex/clickhouse-server:21.11.5.33-alpine
    platform: linux/amd64
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "8124:9000"
    volumes:
      - /Volumes/T7/clickhouse:/var/lib/clickhouse
    extra_hosts:
      - "gruenau2:192.168.65.2"
